### ISSUE TITLE
Music Not Playing

### ISSUE THREAD

**Issue by ardissaps** [MoonflowerTeam/anchor#6]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Finally i does not crash, but idk lately did not hear any music since the mod installed even music from vanilla is not appearing (I am installing this alongside charmonium), the disc still play tho.
```

### latest.log

```shell
https://aofpaste.com/wohigarevu.yaml
```

**Comment by jacksonhardaway** [comment]
Anchor adds music into vanilla sound events, if it's not playing then something is overriding it (likely charmonium). This is not an issue with Anchor.
